### ISSUE TITLE
几点疑惑，望解答

### ISSUE THREAD

**Issue by orangelckc** [GreptimeTeam/dashboard#203]
1. `arco-vue`应该是支持`auto-import`的，没有必要在`main.ts`里全局引入，建议简化，缩小打包大小
```ts
// vite.config.ts
import { ArcoResolver } from 'unplugin-vue-components/resolvers'

AutoImport({
      ...
      imports: [
        ...
        {
          '@arco-design/web-vue': ['Message']
        }
      ],
      resolvers: [ArcoResolver()],
}),
Components({
      ...
      resolvers: [
        ArcoResolver({
          resolveIcons: true
        })
      ]
    }),
```

2. 项目中使用了`auto-import`，需要简化`vue`/`vue-router`/`pinia`/`vue-i18n`的`import`代码，目前存在很多没必要的引入以及`type`定义
3. 数据持久化可以使用`pinia`持久化插件`pinia-plugin-persistedstate`，不需要额外再添加`vueuse`
4. 建议使用`pinia` Composition API 的写法来定义`store`，更符合`vue3`用法
5. 看到了国际化支持，但是没找到设置语言的位置
6. 国际化`locale`拆散了放在组件中，i18n插件识别不到，不知道你们怎么解决的？
7. 建议替换`social-link`代码中 `v-html`的部分

**Comment by ZonaHex** [comment]
First of all, thanks a lot for your advice and support! It means a lot to us! I will reply to your questions in English in the hope that more developers in the world could understand us.

> 1. `arco-vue`应该是支持`auto-import`的，没有必要在`main.ts`里全局引入，建议简化，缩小打包大小

Thanks! I'm not very familiar with `auto-import`, so I will dig more into this.

> 3\. 数据持久化可以使用`pinia`持久化插件`pinia-plugin-persistedstate`，不需要额外再添加`vueuse`

Great advice! I thought about using the plug-in but haven't done it. I will try to use it in the future.

> 4\. 建议使用`pinia` Composition API 的写法来定义`store`，更符合`vue3`用法

Also great advice! At first, Arco's code uses Option API for their `appStore` and we didn't change that. But we realized that Composition API is a better choice, so we are gradually migrating from Option API to Composition API. You might notice some of the stores are Option API (old stores) while others are Composition API (new stores). 

> 5\. 看到了国际化支持，但是没找到设置语言的位置

Right now we only provide the English version so there is no switch for language setting. The Chinese version are in the plan.

> 6\. 国际化`locale`拆散了放在组件中，i18n插件识别不到，不知道你们怎么解决的？

Not sure what you mean...We already import the `locale` from other components so that i18n will work.
`import localeDataExplorer from '@/views/dashboard/locale/en-US'`
Perhaps you mean there isn't anything in the `zh-CN.ts` of the `locale` under `dashboard`? Once we add all the Chinese, it should be correctly translated.

> 7\. 建议替换`social-link`代码中 `v-html`的部分

Thanks! Will get into this as soon as possible.

**Comment by ZonaHex** [comment]
> 2\. 项目中使用了`auto-import`，需要简化`vue`/`vue-router`/`pinia`/`vue-i18n`的`import`代码，目前存在很多没必要的引入以及`type`定义

Actually, I'm using some unnecessary `import` because I want to `cmd` + click and jump to the original code as quickly as possible. Maybe you have some better ways?

**Comment by orangelckc** [comment]
For `i18n`, based on my experience, using a nested structure definition is much easier to configure. It's better to use locale definition files in `.json` or `.yml` format instead of `.ts`, as the `i18n` plugin will consider it as a source file that needs to be translated.

You may find [this](https://github.com/lokalise/i18n-ally) helpful in better understanding my opinion.

**Comment by orangelckc** [comment]
> > 2. 项目中使用了`auto-import`，需要简化`vue`/`vue-router`/`pinia`/`vue-i18n`的`import`代码，目前存在很多没必要的引入以及`type`定义
> 
> Actually, I'm using some unnecessary `import` because I want to `cmd` + click and jump to the original code as quickly as possible. Maybe you have some better ways?

In `components.d.ts` all components all imported using `UpperCamelCase `, but in code it is used with `kebab-case`, that's maybe the reason failed to jump.

**Comment by orangelckc** [comment]
Just tested, not the NAME issue, just add `npm i -D @vue/runtime-core`, it will support the `vue` components to jump. But for my own, I used to use `UpperCamelCase ` as the component name.

**Comment by ZonaHex** [comment]
Hello, again! Thank you so much for all your feedback and following support! Sorry for the late reply...We were occupied with launching a new feature called Playground this past week, and I forgot to reply to you.
I 

> For `i18n`, based on my experience, using a nested structure definition is much easier to configure. It's better to use locale definition files in `.json` or `.yml` format instead of `.ts`, as the `i18n` plugin will consider it as a source file that needs to be translated.
> 
> You may find [this](https://github.com/lokalise/i18n-ally) helpful in better understanding my opinion.

I took a look at this page but haven't got much time to really do some research. Sorry I don't have much experience with i18n, so I sort of did everything based on what Arco Design already built...But I also did a little i18n demo branch last week. You could check it out  [here](https://github.com/GreptimeTeam/dashboard/compare/feat/i18n-switch) if you are interested.
Thank you again for your insights! There are so many things for me to learn from the community and I'm thrilled to discuss with you : )





> Just tested, not the NAME issue, just add `npm i -D @vue/runtime-core`, it will support the `vue` components to jump. But for my own, I used to use `UpperCamelCase ` as the component name.

@alili and I tried this but somehow didn't succeed. I' m not sure what went wrong and I will dig more into this. I really hope we could solve this.

Enjoy your weekend!

**Comment by ZonaHex** [comment]
Close this issue for now. You are welcome to reopen it anytime if you have further comments. Bye!
